{
	"version": 1672990507,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/rock-sheet0.png",
		"images/стекло-sheet0.png",
		"images/mon-sheet0.png",
		"images/mon-sheet1.png",
		"images/земля-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/fire-sheet0.png",
		"images/addhp-sheet0.png",
		"images/portal-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/sprite-sheet0.png",
		"images/сундук-sheet0.png",
		"images/сундук-sheet1.png",
		"images/newgame-sheet0.png",
		"images/exit-sheet0.png",
		"images/menu.png",
		"images/town.png",
		"images/stone.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/сбор монет.m4a",
		"media/сбор монет.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}